### ISSUE TITLE
Assertion error in verifyModule

### ISSUE THREAD

**Issue by nick-ulle** [duncantl/Rllvm#6]
If an LLVM module calls a function using the wrong type of argument, then attempting to verify that module with `verifyModule` results in an assertion error.

Minimal example:
```R
library(Rllvm)

mod = Module('example.ll')

foo = Function('foo', Int32Type, list(), mod)
bar = Function('bar', Int32Type, paramTypes=list(SEXPType), mod)

entry_block = Block(foo, 'entry')
ir = IRBuilder(entry_block)

createCall(ir, bar, createDoubleConstant(3.14))
createRet(ir, createIntegerConstant(0))

showModule(mod)

# WARNING: this line will abort R.
verifyModule(mod)
```
Output:
```
R: wcsrtombs.c:98: __wcsrtombs: Assertion `data.__outbuf[-1] == '\0'' failed.
Aborted (core dumped)
```

**Comment by duncantl** [comment]
Hi Nick
  I think I may have figured out what the problem was (% characters in the code that was being
used as the error message. That interaction with the printf functions and bad things happen!)
So I have committed a change to R/module.R and src/Module.cpp  and this behaves nicely for me,
i.e. gives me the error message at the R level.
I wasn't getting the segfault, but I think that is different random memory configuration and *printf() interpreting the % relative to that.   But I could be wrong. Moving quickly.

**Comment by nick-ulle** [comment]
This seems to be resolved now.
